name: "Code quality"

on:
    workflow_dispatch:
        inputs:
            branch:
                description: "Choose the branch to check"
                type: string
                default: "main"
            repository:
                description: "Choose the repository to check, when using a fork"
                type: string
                default: "dbt-labs/dbt-athena"

permissions:
    contents: read

jobs:
    code-quality:
        uses: dbt-labs/dbt-adapters/.workflows/_code-quality.yml@monorepo-prep
        with:
            branch: ${{ inputs.branch }}
            repository: ${{ inputs.repository }}
