name: "Unit tests"

on:
    workflow_dispatch:
        inputs:
            package:
                description: "Choose the package to test"
                type: choice
                options: ["dbt-athena", "dbt-athena-community"]
            branch:
                description: "Choose the branch to test"
                type: string
                default: "main"
            repository:
                description: "Choose the repository to test, when using a fork"
                type: string
                default: "dbt-labs/dbt-athena"
            os:
                description: "Choose the OS to test against"
                type: string
                default: ${{ vars.DEFAULT_RUNNER }}
            python-version:
                description: "Choose the Python version to test against"
                type: choice
                options: ["3.9", "3.10", "3.11", "3.12"]

permissions:
    contents: read

jobs:
    unit-tests:
        uses: dbt-labs/dbt-adapters/.github/workflows/_unit-tests.yml@monorepo-prep
        with:
            package: ${{ inputs.package }}
            branch: ${{ inputs.branch }}
            repository: ${{ inputs.repository }}
            os: ${{ inputs.os }}
            python-version: ${{ inputs.python-version }}
